name: Go Test Setup
description: Set up the environment for go test
runs:
  using: "composite"
  steps:
    - name: Common setup
      shell: bash
      run: |
        echo 'CGO_ENABLED=1' >> $GITHUB_ENV
    - name: Linux setup
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install gcc-multilib
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libssl-dev:i386
        echo 'CC_FOR_linux_386=i686-w64-mingw32-gcc'
